# Name of the project
PROJECT_NAME = Medical store System

# All source code files
SRC = medical_store_system.c\
src/system main.c
OBJ = system main.o
INC = inc
CFLAGS = I$(INC)
a.out:$(OBJ)
   gcc $ -I$(INC)-o $@
%.o:src%
   gcc $^ -I$(INC)-c
run : target
   ./all.out
clear:
   rm all.out *.o src/*.o
   

